/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import java.awt.Component;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Alumno
 */
public class panell extends javax.swing.JFrame {

    ImageIcon logoICON = new ImageIcon(getClass().getResource("/resources/logo.jpg"));

    ImageIcon fondoICON = new ImageIcon(getClass().getResource("/resources/fondo.jpg"));

    public panell() {
        initComponents();
        ajustesVisuales();
        System.out.println(logoICON.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        altaButton = new javax.swing.JButton();
        tratamientoButton = new javax.swing.JButton();
        liberacionButton = new javax.swing.JButton();
        listadoButton = new javax.swing.JButton();
        bajaButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        logoLABEL = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        fondoLABEL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(242, 244, 243));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(74, 64, 99));

        altaButton.setBackground(new java.awt.Color(200, 198, 215));
        altaButton.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        altaButton.setForeground(new java.awt.Color(120, 63, 142));
        altaButton.setText("Alta");
        altaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaButtonActionPerformed(evt);
            }
        });

        tratamientoButton.setBackground(new java.awt.Color(200, 198, 215));
        tratamientoButton.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        tratamientoButton.setForeground(new java.awt.Color(120, 63, 142));
        tratamientoButton.setText("Tratamiento\n\n");
        tratamientoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamientoButtonActionPerformed(evt);
            }
        });

        liberacionButton.setBackground(new java.awt.Color(200, 198, 215));
        liberacionButton.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        liberacionButton.setForeground(new java.awt.Color(120, 63, 142));
        liberacionButton.setText("Liberar\n");

        listadoButton.setBackground(new java.awt.Color(200, 198, 215));
        listadoButton.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        listadoButton.setForeground(new java.awt.Color(120, 63, 142));
        listadoButton.setText("Listado");

        bajaButton.setBackground(new java.awt.Color(200, 198, 215));
        bajaButton.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        bajaButton.setForeground(new java.awt.Color(120, 63, 142));
        bajaButton.setText("Dar Baja");

        salirButton.setBackground(new java.awt.Color(204, 0, 0));
        salirButton.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        salirButton.setForeground(new java.awt.Color(255, 255, 255));
        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(logoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(liberacionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listadoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bajaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tratamientoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(altaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tratamientoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(liberacionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 500));

        contenedor.setBackground(new java.awt.Color(191, 172, 200));
        contenedor.setLayout(new java.awt.BorderLayout());
        jPanel2.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 620, 420));
        jPanel2.add(fondoLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed
    altaMeow e = new altaMeow();

    private void altaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaButtonActionPerformed
        System.out.println("asd");
        contenedor.removeAll();
        contenedor.add(e);

        // Revalida el contenedor para que los cambios se apliquen correctamente
        contenedor.revalidate();

        // Repinta el contenedor para actualizar la interfaz gráfica
        contenedor.repaint();


    }//GEN-LAST:event_altaButtonActionPerformed

    private void tratamientoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamientoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamientoButtonActionPerformed

    private Icon imgToLabel(Component jLabel, ImageIcon img) {
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(jLabel.getWidth(), jLabel.getHeight(), Image.SCALE_DEFAULT));
        return icon;
    }

    private void ajustesVisuales() {
        logoLABEL.setIcon(imgToLabel(logoLABEL, logoICON));
        fondoLABEL.setIcon(imgToLabel(fondoLABEL, fondoICON));
        // LABEL.setIcon(imgToLabel(LABEL, RUTA));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaButton;
    private javax.swing.JButton bajaButton;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel fondoLABEL;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton liberacionButton;
    private javax.swing.JButton listadoButton;
    private javax.swing.JLabel logoLABEL;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton tratamientoButton;
    // End of variables declaration//GEN-END:variables
}
